### ISSUE TITLE
Making No Stones Unturned all checkable

### ISSUE THREAD

**Issue by TobiasBieschke** [halfacandan/PoEUserScripts#3]
Maybe its worth changing
`var lores = $("table.wikitable:not(table.wikitable:eq(0),table.responsive-table) tbody tr td:nth-child(1)");`
to
`var lores = $("table tbody tr td:nth-child(1)");`

I think its much nicer if you can click every row of the full table instead of only once per act line. This solution is my hacky approach to changing this, as I have no idea what I am doing here, but it works for me 😄 

You could even disable the checkboxes of the acts themselves by changing it to:
`var lores = $("table.sortable tbody tr td:nth-child(1)");`

**Comment by halfacandan** [comment]
Thanks for flagging this. it looks like the wiki page was restructured. I've applied your suggested fix as part of this commit: https://github.com/halfacandan/PoEUserScripts/commit/34ca96f17fda0305d330fadda8c4b957c0230ae7
